apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-demo
  namespace: finops
  labels:
    app: platform-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-demo
  template:
    metadata:
      labels:
        app: platform-demo
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: platform-demo
  namespace: finops
spec:
  selector:
    app: platform-demo
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
